version: 2


updates:

  - package-ecosystem: "docker"
    directories:
      - "/scan/tvchannels-scan/build/"
      - "/epgstation/build/"
      - "/mirakurun/build/"
      - "/scan/isdb-scanner/build/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "library/node"
        update-types: ["version-update:semver-major"]
      - dependency-name: "library/buildpack-deps"
        versions: ["> 24.04", "< 25.0"]
      - dependency-name: "library/buildpack-deps"
        versions: [">= 25.0"]

      
  - package-ecosystem: "docker-compose"
    directories:
      - "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"