version: 2


updates:

  - package-ecosystem: "docker"
    directories:
      - "/tvchannels-scan/"
      - "/mirakc/"
      - "/mirakurun/"
      - "/chinachu/"
      - "/epgstation/"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
