version: 2


updates:

  - package-ecosystem: "docker"
    directories:
      - "/tvchannels-scan/"
      - "/mirakc/"
      - "/mirakurun/"
      - "/chinachu/"
      - "/epgstation/"
      - "/isdb-scanner/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "library/node"
        update-types: ["version-update:semver-major"]
      - dependency-name: "library/buildpack-deps"
        versions: ["> 24.04", "< 25.0"]
      - dependency-name: "library/buildpack-deps"
        versions: [">= 25.0"]

      
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"