services:
  mirakurun:
    image: ghcr.io/stu2005/mirakurun:latest
    container_name: mirakurun
    ports:
      - 40773:40772
    environment:
      - ALLOW_ORIGINS=https://lavie.tailff70c2.ts.net:40772
    devices:
      - /dev/px4video0
      - /dev/px4video1
      - /dev/px4video2
      - /dev/px4video3
      - /dev/pxm1urvideo0
    volumes:
      - mirakurun:/var/run/
      - ./mirakurun/config/:/app-config/
      - mirakurun:/app-data/
    networks:
      - tv-recorder_default
      - caddy_default
    cap_add:
      - SYS_ADMIN
      - SYS_NICE
    device_cgroup_rules:
      - c *:* rmw
    tmpfs:
      - /tmp
    restart: always
    logging:
      driver: json-file
      options:
        max-file: "2"
        max-size: 5m
        compress: "true"
    labels:
      - com.centurylinklabs.watchtower.enable=false
  mariadb:
    image: library/mariadb:latest
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - tv-recorder_default
    environment:
      - MYSQL_USER=epgstation
      - MYSQL_PASSWORD=epgstation
      - MYSQL_ROOT_PASSWORD=epgstation
      - MYSQL_DATABASE=epgstation
      - TZ=Asia/Tokyo
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      --performance-schema=false --binlog-expire-logs-seconds=86400
    restart: always
    logging:
      driver: json-file
      options:
        max-file: "2"
        max-size: 5m
        compress: "true"
    healthcheck:
      test:
        - CMD-SHELL
        - mariadb-admin ping -h localhost || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    labels:
      - com.centurylinklabs.watchtower.enable=false
  epgstation:
    image: ghcr.io/stu2005/epgstation:latest
    container_name: epgstation
    ports:
      - 8889:8888
    volumes:
      - ./epgstation/config/:/app/config/
      - epgstation:/app/data/
      - epgstation:/app/thumbnail/
      - epgstation:/app/logs/
      - /mnt/hdd/recorded/:/app/recorded/
      - ./epgstation/jls/JL/:/usr/local/share/.config/yarn/global/node_modules/join_logo_scp_trial/JL/
      - ./epgstation/jls/logo/:/usr/local/share/.config/yarn/global/node_modules/join_logo_scp_trial/logo/
      - ./epgstation/jls/result/:/usr/local/share/.config/yarn/global/node_modules/join_logo_scp_trial/result/
      - ./epgstation/jls/setting/:/usr/local/share/.config/yarn/global/node_modules/join_logo_scp_trial/setting/
      - ./epgstation/jls/src/:/usr/local/share/.config/yarn/global/node_modules/join_logo_scp_trial/src/
    depends_on:
      - mirakurun
      - mariadb
    networks:
      - tv-recorder_default
      - caddy_default
    devices:
      - /dev/dri:/dev/dri
    restart: always
    logging:
      driver: json-file
      options:
        max-file: "2"
        max-size: 5m
        compress: "true"
    labels:
      - com.centurylinklabs.watchtower.enable=false
  tvchannels-scan:
    logging:
      driver: json-file
      options:
        max-size: 5m
        max-file: "2"
        compress: "true"
    init: true
    restart: no
    network_mode: none
    devices:
      - /dev/px4video0:/dev/px4video0
      - /dev/px4video2:/dev/px4video2
    container_name: tvchannels-scan
    image: ghcr.io/stu2005/tvchannels-scan:latest
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
      - type: bind
        source: ./scan/tvchannels-scan/
        target: /opt/tvchannels-scan/
    profiles:
      - tvchannels-scan
  isdb-scanner:
    logging:
      driver: json-file
      options:
        max-size: 5m
        max-file: "2"
        compress: "true"
    init: true
    restart: no
    network_mode: none
    devices:
      - /dev/px4video0:/dev/px4video0
      - /dev/px4video1:/dev/px4video1
      - /dev/px4video2:/dev/px4video2
      - /dev/px4video3:/dev/px4video3
      - /dev/pxm1urvideo0:/dev/pxm1urvideo0
    container_name: isdb-scanner
    image: ghcr.io/stu2005/isdb-scanner:latest
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
      - type: bind
        source: ./scan/isdb-scanner/
        target: /app/scanned/
    profiles:
      - isdb-scanner
volumes:
  mirakurun:
    name: mirakurun
    driver: local
  mariadb:
    name: mariadb
    driver: local
  epgstation:
    name: epgstation
    driver: local
networks:
  caddy_default:
    external: true
  tv-recorder_default:
    external: true
