services:

  mirakc:
    image: ghcr.io/stu2005/mirakc:debian
    container_name: mirakc
    init: true
    restart: unless-stopped
    devices:
      - "/dev/bus:/dev/bus"
      - "/dev/px4video0:/dev/px4video0"
      - "/dev/px4video1:/dev/px4video1"
      - "/dev/px4video2:/dev/px4video2"
      - "/dev/px4video3:/dev/px4video3"      
    ports:
      - target: 40772
        published: 40772
    volumes:
      - type: volume
        source: mirakc
        target: /var/lib/mirakc/epg/
      - type: bind
        source: ./mirakc/config.yml
        target: /etc/mirakc/config.yml
        read_only: true
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
        compress: "true"

  mysql:
    image: docker.io/library/mysql:latest
    container_name: mysql
    environment:
      TZ: Asia/Tokyo
      MYSQL_DATABASE: epgstation
      MYSQL_USER: epgstation
      MYSQL_PASSWORD: epgstation
      MYSQL_ROOT_PASSWORD: epgstation
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_as_ci --performance-schema=false --expire_logs_days=1 --default-authentication-plugin=mysql_native_password
    volumes:
      - type: volume
        source: mysql
        target: /var/lib/mysql
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
        compress: "true"

  epgstation:
    image: ghcr.io/stu2005/epgstation:latest
    container_name: epgstation
    devices:
      - "/dev/dri:/dev/dri"
    volumes:
      - type: bind
        source: ./epgstation/
        target: /app/config/
        bind:
          create_host_path: true
      - type: volume
        source: epgstation
        target: /app/data/
      - type: volume
        source: epgstation
        target: /app/thumbnail/
      - type: bind
        source: /mnt/hdd/recorded/
        target: /app/recorded/
        bind:
          create_host_path: true
    depends_on:
      mirakc:
        condition: service_healthy
      mysql:
        condition: service_started
    ports:
      - target: 8888
        published: 8888
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
        compress: "true"

volumes:
  mirakc:
    driver: "local"
    name: mirakc
  mysql:
    driver: "local"
    name: mysql
  epgstation:
    name: epgstation