services:

  mirakc:
    image: docker.io/stu2005/mirakc:latest
    container_name: mirakc
    init: true
    restart: unless-stopped
    devices:
      - "/dev/bus/usb/001/006:/dev/bus/usb/001/006"
    ports:
      - target: 40772
        published: 40772
    volumes:
      - type: volume
        source: mirakc
        target: /var/lib/mirakc/epg/
      - type: bind
        source: ./mirakc/config.yml
        target: /etc/mirakc/config.yml
        read_only: true
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
        compress: "true"

  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Tokyo
      MYSQL_DATABASE: epgstation
      MYSQL_USER: epgstation
      MYSQL_PASSWORD: epgstation
    volumes:
      - type: bind
        source: ./mariadb/
        target: /config/
        bind:
          create_host_path: true
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -hlocalhost -P3306 -uepgstation -pepgstation ping || exit 1
      interval: 10s
      timeout: 3s
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
        compress: "true"

  epgstation:
    image: docker.io/stu2005/epgstation:latest
    container_name: epgstation
    volumes:
      - type: bind
        source: ./epgstation/
        target: /app/config/
        bind:
          create_host_path: true
      - type: volume
        source: epgstation
        target: /app/data/
      - type: volume
        source: epgstation
        target: /app/thumbnail/
      - type: bind
        source: /mnt/hdd/recorded/
        target: /app/recorded/
        bind:
          create_host_path: true
    depends_on:
      mirakc:
        condition: service_healthy
      mariadb:
        condition: service_healthy
    ports:
      - target: 8888
        published: 8888
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
        compress: "true"

volumes:
  epgstation:
    name: epgstation
  mirakc:
    name: mirakc
    driver: local
