services:

  mirakc:
    image: ghcr.io/stu2005/mirakc:debian_pcsckai
    container_name: mirakc
    init: true
    restart: unless-stopped
    devices:
      - "/dev/px4video0:/dev/px4video0"
      - "/dev/px4video1:/dev/px4video1"
      - "/dev/px4video2:/dev/px4video2"
      - "/dev/px4video3:/dev/px4video3"      
    ports:
      - target: 40772
        published: 40772
    volumes:
      - type: volume
        source: mirakc
        target: /var/lib/mirakc/epg/
      - type: bind
        source: ./mirakc/config.yml
        target: /etc/mirakc/config.yml
        read_only: true
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
        compress: "true"

  mariadb:
    image: lscr.io/linuxserver/mariadb:11.4.5
    container_name: mariadb
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Tokyo
      MYSQL_DATABASE: epgstation
      MYSQL_USER: epgstation
      MYSQL_PASSWORD: epgstation
      MYSQL_ROOT_PASSWORD: epgstation
    volumes:
      - type: bind
        source: ./mariadb/
        target: /config/
        bind:
          create_host_path: true
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
        compress: "true"

  epgstation:
    image: ghcr.io/stu2005/epgstation:latest
    container_name: epgstation
    devices:
      - "/dev/dri:/dev/dri"
    volumes:
      - type: bind
        source: ./epgstation/
        target: /app/config/
        bind:
          create_host_path: true
      - type: volume
        source: epgstation
        target: /app/data/
      - type: volume
        source: epgstation
        target: /app/thumbnail/
      - type: bind
        source: /mnt/hdd/recorded/
        target: /app/recorded/
        bind:
          create_host_path: true
    depends_on:
      mirakurun:
        condition: service_healthy
      mariadb:
        condition: service_started
    ports:
      - target: 8888
        published: 8888
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "5m"
        compress: "true"

  edcb:
    image: tsukumijima/edcb:latest
    build:
      context: ./edcb/
    restart: always
    privileged: true
    volumes:
      - type: bind
        source: './edcb/EDCB/'
        target: '/EDCB/'
      - type: bind
        source: '/mnt/hdd/'
        target: '/mnt/'
    depends_on:
      mirakc:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "5m"
        compress: "true"

volumes:
  mirakc:
    driver: "local"
    name: mirakc
  mariadb:
    driver: "local"
    name: mariadb
  epgstation:
    name: epgstation