server:
  addrs:
    - http: 0.0.0.0:40772
epg:
  cache-dir: /var/lib/mirakc/epg
channels:
  - name: BS01/TS0
    type: BS
    channel: BS01_0
    disabled: false
  - name: BS01/TS1
    type: BS
    channel: BS01_1
    disabled: false
  - name: BS01/TS2
    type: BS
    channel: BS01_2
    disabled: false
  - name: BS09/TS0
    type: BS
    channel: BS09_0
    disabled: false
  - name: BS09/TS2
    type: BS
    channel: BS09_2
    disabled: false
  - name: BS13/TS0
    type: BS
    channel: BS13_0
    disabled: false
  - name: BS13/TS1
    type: BS
    channel: BS13_1
    disabled: false
  - name: BS13/TS2
    type: BS
    channel: BS13_2
    disabled: false
  - name: BS15/TS0
    type: BS
    channel: BS15_0
    disabled: false
  - name: BS15/TS2
    type: BS
    channel: BS15_2
    disabled: false
  - name: BS23/TS1
    type: BS
    channel: BS23_1
    disabled: false
  - name: BS23/TS3
    type: BS
    channel: BS23_3
    disabled: false
tuners:
  - name: 'PLEX PX-W3PE5 (Terrestrial) #1'
    types:
      - GR
    command: recpt1 --device /dev/px4video2 {{{channel}}} - -
    disabled: false
  - name: 'PLEX PX-W3PE5 (Terrestrial) #2'
    types:
      - GR
    command: recpt1 --device /dev/px4video3 {{{channel}}} - -
    disabled: false
  - name: 'PLEX PX-W3PE5 (Satellite) #1'
    types:
      - BS
      - CS
    command: recpt1 --device /dev/px4video0 {{{channel}}} - -
    disabled: false
  - name: 'PLEX PX-W3PE5 (Satellite) #2'
    types:
      - BS
      - CS
    command: recpt1 --device /dev/px4video1 {{{channel}}} - -
    disabled: false
filters:
  decode-filter:
    command: arib-b25-stream-test
