services:
  mirakurun:
    image: ghcr.io/stu2005/mirakurun:pcsckai
    container_name: mirakurun
    devices:
      - /dev/px4video0
      - /dev/px4video1
      - /dev/px4video2
      - /dev/px4video3    
    volumes:
      - mirakurun:/var/run/
      - ./mirakurun/config/:/app-config/
      - mirakurun:/app-data/
    network_mode: host
    cap_add:
      - SYS_ADMIN
      - SYS_NICE
    device_cgroup_rules:
      - 'c *:* rmw'
    tmpfs:
      - /tmp
    restart: always
    logging:
      driver: json-file
      options:
        max-file: "2"
        max-size: "5m"
        compress: "true"

volumes:
  mirakurun:
    name: mirakurun_data
    driver: local
