port: 8888
mirakurunPath: http://mirakurun:40772/

# dbtype: sqlite
# sqlite:
#   extensions:
#     - '/hoge/regexp.dylib'
#   regexp: true

dbtype: mysql
mysql:
    host: mariadb
    port: 3306
    user: epgstation
    password: epgstation
    database: epgstation
    charset: utf8mb4

epgUpdateIntervalTime: 10

conflictPriority: 1
recPriority: 2

recordedFormat: '%YEAR%年%MONTH%月%DAY%日%HOUR%時%MIN%分%SEC%秒-%TITLE%'
recordedFileExtension: .ts
recorded:
    - name: recorded
      path: '%ROOT%/recorded'

thumbnail: '%ROOT%/thumbnail'
thumbnailSize: 480x270
thumbnailPosition: 5

ffmpeg: /usr/bin/qsvencc
ffprobe: /usr/bin/ffprobe

encodeProcessNum: 4
concurrentEncodeNum: 1
encode:
    - name: QSV
      cmd: '/usr/bin/qsvencc --avhw -i- -o"%YEAR%年%MONTH%月%DAY%日%HOUR%時%MIN%分%SEC%秒-%TITLE%"'
      suffix: .mp4
      rate: 4.0

urlscheme:
    m2ts:
        ios: vlc-x-callback://x-callback-url/stream?url=PROTOCOL%3A%2F%2FADDRESS
        android: intent://ADDRESS#Intent;action=android.intent.action.VIEW;type=video/*;scheme=PROTOCOL;end
    video:
        ios: infuse://x-callback-url/play?url=PROTOCOL://ADDRESS
        android: intent://ADDRESS#Intent;action=android.intent.action.VIEW;type=video/*;scheme=PROTOCOL;end
    download:
        ios: vlc-x-callback://x-callback-url/download?url=PROTOCOL%3A%2F%2FADDRESS&filename=FILENAME

stream:
    live:
        ts:
            qsv:
                - name: 無変換
                - name: HEVC
                  cmd:
                      '%FFMPEG 
                        --input-format mpegts 
                        --fps 30000/1001 
                        --input - 
                        --avhw 
                        --audio-stream 1?:stereo 
                        --audio-stream 2?:stereo 
                        --data-copy timed_id3
                        -m avioflags:direct 
                        -m fflags:nobuffer+flush_packets 
                        -m flush_packets:1 
                        -m max_delay:250000
                        --output-thread 0 
                        --lowlatency
                        --disable-opencl
                        --codec hevc
                        --fallback-rc
                        --qvbr-quality 30
                        --quality balanced
                        --profile main
                        --dar 16:9
                        --interlace tff
                        --vpp-deinterlace normal
                        --avsync vfr
                        --output-res 1920x1080
                        --audio-codec aac:aac_coder=twoloop
                        --audio-samplerate 48000 
                        --audio-filter volume=2.0 
                        --audio-ignore-decode-error 30
                        --output-format mpegts
                        --output -'
                - name: H264
                  cmd: 
                      '%FFMPEG%
                        --input-format mpegts
                        --fps 30000/1001
                        --input -
                        --avhw
                        --audio-stream 1?:stereo 
                        --audio-stream 2?:stereo 
                        --data-copy timed_id3
                        -m avioflags:direct 
                        -m fflags:nobuffer+flush_packets 
                        -m flush_packets:1 
                        -m max_delay:250000
                        --output-thread 0 
                        --lowlatency
                        --disable-opencl
                        --codec h264
                        --quality balanced
                        --profile high
                        --dar 16:9
                        --interlace tff
                        --vpp-deinterlace normal
                        --avsync vfr
                        --output-res 1920x1080
                        --audio-codec aac:aac_coder=twoloop
                        --audio-samplerate 48000 
                        --audio-filter volume=2.0 
                        --audio-ignore-decode-error 30
                        --output-format mpegts
                        --output -'
    recorded:
        ts:
            qsv:
                - name: HEVC
                  cmd:
                      '%FFMPEG%
                        --input-format mpegts
                        --input -
                        --avhw
                        --audio-stream 1?:stereo 
                        --audio-stream 2?:stereo 
                        --data-copy timed_id3
                        -m avioflags:direct 
                        -m fflags:nobuffer+flush_packets 
                        -m flush_packets:1 
                        -m max_delay:0
                        --disable-opencl
                        --codec hevc
                        --fallback-rc
                        --qvbr-quality 30
                        --strict-gop
                        --quality balanced
                        --profile main
                        --dar 16:9
                        --vpp-deinterlace bob
                        --avsync vfr
                        --output-res 1920x1080
                        --audio-codec aac:aac_coder=twoloop
                        --audio-samplerate 48000 
                        --audio-filter volume=2.0 
                        --audio-ignore-decode-error 30
                        --output-format mpegts
                        --output -'
                - name: H264
                  cmd:
                      '%FFMPEG
                        --input-format mpegts
                        --input -
                        --avhw
                        --audio-stream 1?:stereo 
                        --audio-stream 2?:stereo 
                        --data-copy timed_id3%
                        --disable-opencl
                        --codec h264
                        --strict-gop
                        --quality balanced
                        --dar 16:9
                        --interlace tff
                        --vpp-deinterlace bob
                        --avsync vfr
                        --output-res 1920x1080
                        --audio-codec aac:aac_coder=twoloop
                        --audio-samplerate 48000 
                        --audio-filter volume=2.0 
                        --audio-ignore-decode-error 30
                        --output-format mpegts
                        --output -'

        encoded:
            qsv:
                - name: HEVC
                  cmd:
                      '%FFMPEG%
                        --input-format mpegts
                        --input -
                        --avhw
                        --audio-stream 1?:stereo 
                        --audio-stream 2?:stereo 
                        --data-copy timed_id3
                        -m avioflags:direct 
                        -m fflags:nobuffer+flush_packets 
                        -m flush_packets:1 
                        -m max_delay:0
                        --disable-opencl
                        --codec hevc
                        --fallback-rc
                        --qvbr-quality 30
                        --strict-gop
                        --quality balanced
                        --profile main
                        --dar 16:9
                        --vpp-deinterlace bob
                        --avsync vfr
                        --output-res 1920x1080
                        --audio-codec aac:aac_coder=twoloop
                        --audio-samplerate 48000 
                        --audio-filter volume=2.0 
                        --audio-ignore-decode-error 30
                        --output-format mpegts
                        --output -'
                - name: H264
                  cmd:
                      '%FFMPEG
                        --input-format mpegts
                        --input -
                        --avhw
                        --audio-stream 1?:stereo 
                        --audio-stream 2?:stereo 
                        --data-copy timed_id3%
                        --disable-opencl
                        --codec h264
                        --strict-gop
                        --quality balanced
                        --dar 16:9
                        --interlace tff
                        --vpp-deinterlace bob
                        --avsync vfr
                        --output-res 1920x1080
                        --audio-codec aac:aac_coder=twoloop
                        --audio-samplerate 48000 
                        --audio-filter volume=2.0 
                        --audio-ignore-decode-error 30
                        --output-format mpegts
                        --output -'                