port: 8888
mirakurunPath: http://mirakurun:40772/

kodiHosts:
    - name: Fire TV Stick HD
      host: http://192.168.1.101:8090

# dbtype: sqlite
# sqlite:
#   extensions:
#     - '/hoge/regexp.dylib'
#   regexp: true

dbtype: mysql
mysql:
    host: mariadb
    port: 3306
    user: epgstation
    password: epgstation
    database: epgstation
    charset: utf8mb4

epgUpdateIntervalTime: 10

conflictPriority: 1
recPriority: 2

recordedFormat: '%YEAR%年%MONTH%月%DAY%日%HOUR%時%MIN%分%SEC%秒-%TITLE%'
recordedFileExtension: .ts
recorded:
    - name: recorded
      path: '%ROOT%/recorded'
      limitThreshold: 100000
      action: remove
      
thumbnail: '%ROOT%/thumbnail'
thumbnailSize: 480x270
thumbnailPosition: 5

ffmpeg: /usr/bin/ffmpeg
ffprobe: /usr/bin/ffprobe

encodeProcessNum: 4
concurrentEncodeNum: 1
encode:
    - name: H.264
      cmd: '%NODE% %ROOT%/config/enc.js'
      suffix: .mp4
      rate: 4.0

urlscheme:
    m2ts:
        ios: vlc-x-callback://x-callback-url/stream?url=PROTOCOL%3A%2F%2FADDRESS
        android: intent://ADDRESS#Intent;action=android.intent.action.VIEW;type=video/*;scheme=PROTOCOL;end
    video:
        ios: infuse://x-callback-url/play?url=PROTOCOL://ADDRESS
        android: intent://ADDRESS#Intent;action=android.intent.action.VIEW;type=video/*;scheme=PROTOCOL;end
    download:
        ios: vlc-x-callback://x-callback-url/download?url=PROTOCOL%3A%2F%2FADDRESS&filename=FILENAME

stream:
    live:
        ts:
            m2ts:
                - name: 無変換
                - name: 1080p
                  cmd:
                      '%FFMPEG% -re -dual_mono_mode main -c:v mpeg2_qsv -i pipe:0 -sn -threads 0 -c:a aac -ar 48000 -b:a 192k -ac 2
                      -c:v h264_qsv -vf bwdif=1:-1:1,scale=-2:1080 -b:v 6000k -preset veryfast -y -f mpegts pipe:1'
                - name: 720p
                  cmd:
                      '%FFMPEG% -re -dual_mono_mode main -c:v mpeg2_qsv -i pipe:0 -sn -threads 0 -c:a aac -ar 48000 -b:a 192k -ac 2
                      -c:v h264_qsv -vf bwdif=1:-1:1,scale=-2:720 -b:v 3000k -preset veryfast -y -f mpegts pipe:1'
                - name: 480p
                  cmd:
                      '%FFMPEG% -re -dual_mono_mode main -c:v mpeg2_qsv -i pipe:0 -sn -threads 0 -c:a aac -ar 48000 -b:a 128k -ac 2
                      -c:v h264_qsv -vf bwdif=1:-1:1,scale=-2:480 -b:v 1500k -preset veryfast -y -f mpegts pipe:1'

            m2tsll:
                - name: 1080p
                  cmd:
                      '%FFMPEG% -dual_mono_mode main -f mpegts -analyzeduration 500000 -c:v mpeg2_qsv -i pipe:0 -map 0 -c:s copy -c:d
                      copy -ignore_unknown -fflags nobuffer -flags low_delay -max_delay 250000 -max_interleave_delta 1
                      -threads 0 -c:a aac -ar 48000 -b:a 192k -ac 2 -c:v h264_qsv -flags +cgop -vf bwdif=1:-1:1,scale=-2:1080
                      -b:v 6000k -preset veryfast -y -f mpegts pipe:1'
                - name: 720p
                  cmd:
                      '%FFMPEG% -dual_mono_mode main -f mpegts -analyzeduration 500000 -c:v mpeg2_qsv -i pipe:0 -map 0 -c:s copy -c:d
                      copy -ignore_unknown -fflags nobuffer -flags low_delay -max_delay 250000 -max_interleave_delta 1
                      -threads 0 -c:a aac -ar 48000 -b:a 192k -ac 2 -c:v h264_qsv -flags +cgop -vf bwdif=1:-1:1,scale=-2:720
                      -b:v 3000k -preset veryfast -y -f mpegts pipe:1'
                - name: 480p
                  cmd:
                      '%FFMPEG% -dual_mono_mode main -f mpegts -analyzeduration 500000 -c:v mpeg2_qsv -i pipe:0 -map 0 -c:s copy -c:d
                      copy -ignore_unknown -fflags nobuffer -flags low_delay -max_delay 250000 -max_interleave_delta 1
                      -threads 0 -c:a aac -ar 48000 -b:a 128k -ac 2 -c:v h264_qsv -flags +cgop -vf bwdif=1:-1:1,scale=-2:480
                      -b:v 1500k -preset veryfast -y -f mpegts pipe:1'

            mp4:
                - name: 1080p
                  cmd:
                      '%FFMPEG% -re -dual_mono_mode main -c:v mpeg2_qsv -i pipe:0 -sn -threads 0 -c:a aac -ar 48000 -b:a 192k -ac 2
                      -c:v h264_qsv -vf bwdif=1:-1:1,scale=-2:1080 -b:v 6000k -profile:v baseline -preset veryfast -tune
                      fastdecode,zerolatency -movflags frag_keyframe+empty_moov+faststart+default_base_moof -y -f mp4
                      pipe:1'
                - name: 720p
                  cmd:
                      '%FFMPEG% -re -dual_mono_mode main -c:v mpeg2_qsv -i pipe:0 -sn -threads 0 -c:a aac -ar 48000 -b:a 192k -ac 2
                      -c:v h264_qsv -vf bwdif=1:-1:1,scale=-2:720 -b:v 3000k -profile:v baseline -preset veryfast -tune
                      fastdecode,zerolatency -movflags frag_keyframe+empty_moov+faststart+default_base_moof -y -f mp4
                      pipe:1'
                - name: 480p
                  cmd:
                      '%FFMPEG% -re -dual_mono_mode main -c:v mpeg2_qsv -i pipe:0 -sn -threads 0 -c:a aac -ar 48000 -b:a 128k -ac 2
                      -c:v h264_qsv -vf bwdif=1:-1:1,scale=-2:480 -b:v 1500k -profile:v baseline -preset veryfast -tune
                      fastdecode,zerolatency -movflags frag_keyframe+empty_moov+faststart+default_base_moof -y -f mp4
                      pipe:1'
            webm: []
            hls: []

    recorded:
        ts:
            mp4:
                - name: 1080p
                  cmd:
                      '%FFMPEG% -dual_mono_mode main -c:v mpeg2_qsv -i pipe:0 -sn -threads 0 -c:a aac -ar 48000 -b:a 192k -ac 2 -c:v
                      h264_qsv -vf bwdif=1:-1:1,scale=-2:1080 -b:v 6000k -profile:v baseline -preset veryfast -tune
                      fastdecode,zerolatency -movflags frag_keyframe+empty_moov+faststart+default_base_moof -y -f mp4
                      pipe:1'
                - name: 720p
                  cmd:
                      '%FFMPEG% -dual_mono_mode main -c:v mpeg2_qsv -i pipe:0 -sn -threads 0 -c:a aac -ar 48000 -b:a 192k -ac 2 -c:v
                      h264_qsv -vf bwdif=1:-1:1,scale=-2:720 -b:v 3000k -profile:v baseline -preset veryfast -tune
                      fastdecode,zerolatency -movflags frag_keyframe+empty_moov+faststart+default_base_moof -y -f mp4
                      pipe:1'
                - name: 480p
                  cmd:
                      '%FFMPEG% -dual_mono_mode main -c:v mpeg2_qsv -i pipe:0 -sn -threads 0 -c:a aac -ar 48000 -b:a 128k -ac 2 -c:v
                      h264_qsv -vf bwdif=1:-1:1,scale=-2:480 -b:v 1500k -profile:v baseline -preset veryfast -tune
                      fastdecode,zerolatency -movflags frag_keyframe+empty_moov+faststart+default_base_moof -y -f mp4
                      pipe:1'
            webm: []
            hls: []

        encoded:
            mp4:
                - name: 1080p
                  cmd:
                      '%FFMPEG% -dual_mono_mode main -ss %SS% -c:v h264_qsv -i %INPUT% -sn -threads 0 -c:a aac -ar 48000 -b:a 192k -ac
                      2 -c:v h264_qsv -vf scale=-2:1080 -b:v 6000k -profile:v baseline -preset veryfast -tune
                      fastdecode,zerolatency -movflags frag_keyframe+empty_moov+faststart+default_base_moof -y -f mp4
                      pipe:1'
                - name: 720p
                  cmd:
                      '%FFMPEG% -dual_mono_mode main -ss %SS% -c:v h264_qsv -i %INPUT% -sn -threads 0 -c:a aac -ar 48000 -b:a 192k -ac
                      2 -c:v h264_qsv -vf scale=-2:720 -b:v 3000k -profile:v baseline -preset veryfast -tune
                      fastdecode,zerolatency -movflags frag_keyframe+empty_moov+faststart+default_base_moof -y -f mp4
                      pipe:1'
                - name: 480p
                  cmd:
                      '%FFMPEG% -dual_mono_mode main -ss %SS% -c:v h264_qsv -i %INPUT% -sn -threads 0 -c:a aac -ar 48000 -b:a 128k -ac
                      2 -c:v h264_qsv -vf scale=-2:480 -b:v 1500k -profile:v baseline -preset veryfast -tune
                      fastdecode,zerolatency -movflags frag_keyframe+empty_moov+faststart+default_base_moof -y -f mp4
                      pipe:1'
            webm: []
            hls: []
