name: mirakurun


on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - 'mirakurun/**'  
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '29 16 * * *'


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: |
            [registry."docker.io"]
              mirrors = ["registry-1.docker.io", "mirror.gcr.io", "public.ecr.aws/docker"]

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Prune build cache
        run: |
          docker buildx prune --all --force --verbose

      - name: Build and push Mirakurun
        uses: docker/build-push-action@v6
        with:
          context: ./mirakurun/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/stu2005/mirakurun:latest

      - name: Build and push Mirakurun(PCSCkai)
        uses: docker/build-push-action@v6
        with:
          context: ./mirakurun/
          file: ./mirakurun/pcsckai.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/stu2005/mirakurun:pcsckai

      - name: Build and push Mirakurun(Debian)
        uses: docker/build-push-action@v6
        with:
          context: ./mirakurun/
          file: ./mirakurun/debian.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/stu2005/mirakurun:debian

      - name: Build and push Mirakurun(Debian*PCSCkai)
        uses: docker/build-push-action@v6
        with:
          context: ./mirakurun/
          file: ./mirakurun/debian.pcsckai.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/stu2005/mirakurun:debian_pcsckai